### PR TITLE
Added multiple parameter in request

### PR DESCRIPTION
**Pull request by HAghajanyan-ST**
Added possibility to pass multiple parameters with same name in ConsulRequest

### CODE REVIEW

**Comment by HAghajanyan-ST** [comment]
@jgiannuzzi please review PR

**Comment by jgiannuzzi** [comment]
Thanks for your PR, @HAghajanyan-ST!

I will review it soon 👀

**Comment by jgiannuzzi** [comment]
Hi @HAghajanyan-ST, after discussing offline with @marcin-krystianc, we think that we should use [`NameValueCollection`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection?view=netcore-3.1) for storing the request params, as it is a more direct mapping to what HTTP request params are. Could you please update your PR to use this class instead of `Dictionary<string, IList<string>>`?

I really appreciate the time you have already spent on this so far, and I would understand if you wouldn't want to make that change. In that case, just let us know and we can update your PR ourselves, then let you review it before merging.

**Comment by HAghajanyan-ST** [comment]
Hi @jgiannuzzi , thanks for your comment, I didin't use NameValueCollection because, If the specified key already exists in the target NameValueCollection instance, the specified value is added to the existing comma-separated list of values in the form "value1,value2,value3". So in this case we must also check if there is a comma separate the value by comma. If you still think I must change I can do it :) 

Source:
https://stackoverflow.com/questions/21590778/add-duplicates-keys-to-namevaluecollection

**Comment by marcin-krystianc** [comment]
Hi @HAghajanyan-ST,

Thanks for your response. I think that the msdn documentation is misleading 🤷.
`NameValueCaollection` has two ways of getting values: `Get` and `GetValues`.
What you say is correct only for the `Get` method, as it returns a single string with all values joined with the `,`.
However the `GetValues` returns an array of strings, so it is not a problem even if any of these values contains a `,` character.

E.g.:
```
var nameValueCollection = new NameValueCollection();
nameValueCollection.Add("a", "Hello,Hello");
nameValueCollection.Add("a", "World,World");

Console.WriteLine(nameValueCollection.Get("a"));
foreach (var v in nameValueCollection.GetValues("a"))
{
    Console.WriteLine(v);
}
```
```
Hello,Hello,World,World
Hello,Hello
World,World
```

**Comment by jgiannuzzi** [comment]
Hi @HAghajanyan-ST, as @marcin-krystianc explained above, we think that NameValueCollection is the right way to go.
Would you mind adapting your PR to use it, or should we?

**Comment by mfkl** [comment]
Some initial work here. https://github.com/mfkl/consuldotnet/commits/feature/multiple-tags

Rebased and started using `NameValueCollection` instead. It's not ready yet as it appears to be failing some tests, and I'm not too sure on how to go about the `BuildConsulUri` new implementation.

**Comment by mfkl** [comment]
> Do you still think that this change is necessary after the https://github.com/G-Research/consuldotnet/pull/36 was implemented?

Yes, I believe indeed #36 should do it. Feel free to let us know if that works for you @HAghajanyan-ST.

Closing.

**Pull request closed without merging**
