### PR TITLE
Add GenerateDocumentationFile to make summaries show up in IDEs

### PR DESCRIPTION
**Pull request by NielsPilgaard**
Without `GenerateDocumentationFile` set to true, your great code summaries never make it to the developer using the nuget.

### CODE REVIEW

**Review by marcin-krystianc — APPROVED** [review]

**Review by marcin-krystianc — CHANGES_REQUESTED** [review]
Hi @NielsPilgaard,

Thanks for raising this PR. Could you have a look at these build warnings/errors?
```
error CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.' 
```

**Comment by NielsPilgaard** [comment]
> Hi @NielsPilgaard,
> 
> Thanks for raising this PR. Could you have a look at these build warnings/errors?
> 
> ```
> error CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.' 
> ```

Absolutely, I'll have a look tonight 👍

**Comment by NielsPilgaard** [comment]
I hope [this](https://github.com/G-Research/consuldotnet/pull/365/commits/f7a20db569864fb808735a6d105caeb1ac425f40) is an acceptable approach, it was either ignoring warning `CS1591` or adding summaries in over 1700 places 😅

**Review by marcin-krystianc — APPROVED** [review]
> I hope [this](https://github.com/G-Research/consuldotnet/pull/365/commits/f7a20db569864fb808735a6d105caeb1ac425f40) is an acceptable approach, it was either ignoring warning `CS1591` or adding summaries in over 1700 places 😅

Yeah, that makes sense.

Thank you!

**Pull request merged**
