### PR TITLE
Add Consul.AspNetCore CI, refactor project, add options, remove obsol…

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
Add Consul.AspNetCore CI, refactor project, add options, remove obsolete on client ctor, bump version

- Package Consul.AspNetCore is owned by this implementation https://www.nuget.org/packages/Consul.AspNetCore/
- Should we try to contact to zlzforever or use another package name?

**Decisions**
- [x] [**Discussable**] I added separate workflow, because of ci.yml is required to push and all checks have to be passed
- [x] [**Discussable**] `Consul.AspNetCore` workflow called consul.aspnetcore.yaml
- [x] I removed `Obsolete` from `ConsulClient` ctor to integrate with `IOptions`
- [x] I created `IConsulClientFactory` to integrate with `IOptions` and separate from registration logic. Also to use `NamedOptions` and create override with `CreateClient(string name)` to support multiple clients in one process
- [x] [**Discussable**] I used `Consul | AspNetCore | Package | Artifact | Download` names in workflow steps for readability
- [x] [**Discussable**] I used `3.1.8` version like an AspNetCore, should it be a Consul version? Or independant one?
- [x] [**Discussable**] I separated dists to Consul and Consul.AspNetCore to not to pack both .nupkg in artifact. So dist/consul for Consul and dist/consul.aspnetcore for Consul.AspNetCore
- [x] Tests for Consul.AspNetCore runs on windows-latest only, because of no external os specific dependency required and already written script to extract package version

### CODE REVIEW

**Comment by sergeyshaykhullin** [comment]
=(

image

**Comment by mfkl** [comment]
Hi @sergeyshaykhullin,

Thank you for getting things moving on various tasks! 

I think it may be easier to review if you do multiple focused PRs though, as you are currently making several unrelated changes (CI, new/removed APIs, dependencies bump...). Just my pov :-)

**Comment by sergeyshaykhullin** [comment]
@mfkl I can split changes to multiple prs, but for now i have to test all this changes in one

If you want, you can help me with discussion

**Comment by sergeyshaykhullin** [comment]
Fow now i think i am done, i need a feedback
No need to read changes, just **decisions** block above

**Comment by lorinck** [comment]
@sergeyshaykhullin The obsolte note on the constuctor was removed and in master now

**Comment by sergeyshaykhullin** [comment]
@lorinck Merged

**Comment by mfkl** [comment]
This can't be reviewed properly as is, if you want to get this merged, you need to split your work in multiple focused PRs. :-)

**Pull request closed without merging**
