### PR TITLE
Add GRPC and GRPCUseTLS agent check settings

### PR DESCRIPTION
**Pull request by SonicGD**
Add https://www.consul.io/api-docs/agent/check#grpc and https://www.consul.io/api-docs/agent/check#grpcusetls agent check settings

### CODE REVIEW

**Comment by mfkl** [comment]
LGTM

**Comment by rogeralsing** [comment]
Any ETA on this?

**Comment by stackedsax** [comment]
@rogeralsing Sorry for the delay, this one escaped our notice.  @jgiannuzzi should be back around to review and merge in the next couple of days.

**Comment by jgiannuzzi** [comment]
Sorry for the very late reply @SonicGD and @rogeralsing, I am just back from vacation and will look into it!

**Comment by jgiannuzzi** [comment]
Thanks a lot for your contribution to Consul.NET @SonicGD!

**Comment by SonicGD** [comment]
Thank you for merging =)

**Comment by murugaratham** [comment]
is there any example to try this?

**Pull request merged**
