### PR TITLE
Added support for agent version

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
fixes https://github.com/G-Research/consuldotnet/issues/260
@marcin-krystianc  @naskio

### CODE REVIEW

**Review by marcin-krystianc — APPROVED** [review]

**Comment by marcin-krystianc** [comment]
Looks good, but there are conflicts to be resolved.

**Comment by sammychinedu2ky** [comment]
@marcin-krystianc . This one also has breaking change across different consul API

**Comment by sammychinedu2ky** [comment]
@marcin-krystianc . I think I would use the skippable feature here

**Comment by sammychinedu2ky** [comment]
@marcin-krystianc I think I would use the skippable feature here as well

**Comment by marcin-krystianc** [comment]
> @marcin-krystianc . I think I would use the skippable feature here

I think that the problem here is that you didn't specify the json format for output, see https://developer.hashicorp.com/consul/commands/v1.11.x/version#command-options

**Comment by sammychinedu2ky** [comment]
> > @marcin-krystianc . I think I would use the skippable feature here
> 
> I think that the problem here is that you didn't specify the json format for output, see https://developer.hashicorp.com/consul/commands/v1.11.x/version#command-options

Thanks @marcin-krystianc . But that one is for the CLI tool. I am making use of the endpoint
https://developer.hashicorp.com/consul/api-docs/agent#retrieve-version-information

**Comment by sammychinedu2ky** [comment]
done @marcin-krystianc thanks

**Review by marcin-krystianc — APPROVED** [review]

**Comment by marcin-krystianc** [comment]
Nicely done, thank you.

**Pull request merged**
